import { Bell, Check, ShieldCheck } from "lucide-react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function ManagerNotificationCenter({ navigate }: { navigate: (to: string) => void }) {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const notifications = trpc.notifications.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const acknowledge = trpc.notifications.acknowledge.useMutation({
    onSuccess: () => { toast.success("تم تأكيد الاطلاع على الإشعار وسُجل الحدث تشغيلياً."); utils.notifications.listMine.invalidate(); utils.audit.listOperations.invalidate(); },
    onError: () => toast.error("تعذر تأكيد الإشعار ضمن نطاق العيادة."),
  });

  if (!isAuthenticated) return <main className="shell page-wrap"><section className="panel mx-auto max-w-2xl py-12 text-center"><ShieldCheck className="mx-auto text-[#0b776b]" size={34}/><h1 className="mt-4 text-xl font-bold text-[#31584f]">مركز إشعارات محمي</h1><p className="mt-3 text-sm leading-7 text-[#6b867e]">سجّل الدخول بحساب مدير لعرض إشعارات الزيارات المتأخرة وتأكيد الاطلاع عليها.</p><button className="primary-btn mt-6" onClick={() => startLogin()}>تسجيل الدخول</button></section></main>;
  if (notifications.isError) return <main className="shell page-wrap"><section className="panel mx-auto max-w-2xl py-12 text-center"><ShieldCheck className="mx-auto text-[#0b776b]" size={34}/><h1 className="mt-4 text-xl font-bold text-[#31584f]">وصول المدير مطلوب</h1><p className="mt-3 text-sm leading-7 text-[#6b867e]">يقتصر مركز الإشعارات على مديري العيادات النشطة.</p><button className="outline-btn mt-6" onClick={() => navigate("/")}>الرئيسية</button></section></main>;
  const unread = notifications.data?.filter(notification => !notification.acknowledgedAt).length ?? 0;
  return <main className="shell page-wrap"><div className="page-header"><div><h1>مركز الإشعارات</h1><p>تنبيهات داخل التطبيق للزيارات المتأخرة في عيادات المدير، دون إرسال بيانات إلى خدمة خارجية.</p></div><button className="outline-btn" onClick={() => navigate("/operations")}>لوحة التشغيل</button></div><section className="metric-grid"><div className="metric-card"><span className="metric-label">غير مؤكدة</span><span className="metric-value">{unread}</span></div><div className="metric-card"><span className="metric-label">الإشعارات المعروضة</span><span className="metric-value">{notifications.data?.length ?? 0}</span></div></section><section className="panel mt-5"><div className="section-head"><div><h2 className="section-title">التنبيهات الأخيرة</h2><p className="section-copy">يُنشأ إشعار واحد لكل زيارة متأخرة وللمدير نفسه، ويُحفظ تأكيد الاطلاع بشكل مستقل في سجل التدقيق التشغيلي.</p></div></div>{notifications.isLoading ? <p className="py-5 text-sm text-[#6f887f]">جارٍ تحميل الإشعارات…</p> : <div className="grid gap-3">{notifications.data?.map(notification => <article key={notification.id} className={`rounded-2xl border p-5 ${notification.acknowledgedAt ? "border-[#dbe9e4] bg-[#fbfefd]" : "border-[#f4d5a8] bg-[#fffaf0]"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-[#e7f6f1] text-[#0b776b]"><Bell size={18}/></span><div><h3 className="font-bold text-[#31584f]">{notification.title}</h3><p className="mt-1 text-sm text-[#6b867e]">{notification.message}</p></div></div>{notification.acknowledgedAt ? <span className="badge badge-success">تم الاطلاع</span> : <button className="outline-btn" disabled={acknowledge.isPending} onClick={() => acknowledge.mutate({ notificationId: notification.id })}><Check className="ml-1" size={15}/> تأكيد الاطلاع</button>}</div><p className="mt-4 text-xs text-[#718980]">{notification.acknowledgedAt ? `تم التأكيد: ${new Date(notification.acknowledgedAt).toLocaleString("ar-SA")}` : `أنشئ: ${new Date(notification.createdAt).toLocaleString("ar-SA")}`}</p></article>)}{notifications.data?.length === 0 && <div className="rounded-2xl bg-[#f5faf8] p-6 text-center text-sm text-[#6b867e]">لا توجد إشعارات تشغيلية ضمن عياداتك حالياً.</div>}</div>}</section></main>;
}
